# Auto-generated by oo_metrics_plus.py
$env:DL_P_LONG_MODE = "abs"
$env:DL_P_LONG      = "0.428080"
$env:META_KINDS     = "tx"
$env:DL_LOG_PATH    = "live_meta_log.csv"
Write-Host "Set DL_P_LONG=0.428080 (bucket p95)."
