# Auto-generated by oo_metrics_plus.py
$env:DL_P_LONG_MODE = "abs"
$env:DL_P_LONG      = "0.421342"
$env:META_KINDS     = "tcn"
$env:DL_LOG_PATH    = "live_meta_log.csv"
Write-Host "Set DL_P_LONG=0.421342 (bucket p50)."
